Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/environments/*"
    - "config/routes.rb"
Layout/LineLength:
  Exclude:
    - "config/**/*"
    - "Gemfile"
    - "Rakefile"
