version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/app
      - gem_cache_app:/gems
    env_file:
      - .env/development
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server

  scraper:
    build:
      context: ../scraper/.
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    volumes:
      - ../scraper/:/var/www/app
      - gem_cache_scraper:/gems
    env_file:
      - .env/development

  webpack_dev_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/var/www/app
      - gem_cache_app:/gems
    env_file:
      - .env/development
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis_cache
    volumes:
      - .:/var/www/app
      - gem_cache_app:/gems
    env_file:
      - .env/development

  redis_cache:
    image: redis
    volumes:
      - redis_cache_data:/docker/redis-cache-data

  database:
    image: postgres
    env_file:
      - .env/development
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672

  sneakers:
    build: ../scraper/.
    volumes:
      - .:/sneakers
    depends_on:
      - rabbitmq
      - redis_cache
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

volumes:
  db_data:
  gem_cache_app:
  gem_cache_scraper:
  redis_cache_data:
